smpp.host=localhost
smpp.port=2775
smpp.system_id=smppclient1
smpp.password=password
smpp.system_type=
smpp.source_addr=OTPService
smpp.source_addr_ton=5
smpp.source_addr_npi=0
smpp.dest_addr_ton=1
smpp.dest_addr_npi=1
